/* Resource file indices for AES_APP. */

#define MENU             0   /* Menu-tree */
#define M_DESK           3   /* TITLE in tree MENU */
#define M_FILE           4   /* TITLE in tree MENU */
#define M_DESK_INFO      7   /* STRING in tree MENU */
#define M_FILE_QUIT      16  /* STRING in tree MENU */

#define FORM             1   /* Form/Dialog-box */
#define FORM_ROOT        0   /* BOX in tree FORM */
#define NUM_BTN          1   /* BUTTON in tree FORM */
#define A_BTN            2   /* BUTTON in tree FORM */
#define B_BTN            3   /* BUTTON in tree FORM */
#define C_BTN            4   /* BUTTON in tree FORM */
#define D_BTN            5   /* BUTTON in tree FORM */
#define E_BTN            6   /* BUTTON in tree FORM */
#define F_BTN            7   /* BUTTON in tree FORM */
#define G_BTN            8   /* BUTTON in tree FORM */
#define H_BTN            9   /* BUTTON in tree FORM */
#define I_BTN            10  /* BUTTON in tree FORM */
#define J_BTN            11  /* BUTTON in tree FORM */
#define K_BTN            12  /* BUTTON in tree FORM */
#define L_BTN            13  /* BUTTON in tree FORM */
#define M_BTN            14  /* BUTTON in tree FORM */
#define N_BTN            15  /* BUTTON in tree FORM */
#define O_BTN            16  /* BUTTON in tree FORM */
#define P_BTN            17  /* BUTTON in tree FORM */
#define Q_BTN            18  /* BUTTON in tree FORM */
#define R_BTN            19  /* BUTTON in tree FORM */
#define S_BTN            20  /* BUTTON in tree FORM */
#define T_BTN            21  /* BUTTON in tree FORM */
#define U_BTN            22  /* BUTTON in tree FORM */
#define V_BTN            23  /* BUTTON in tree FORM */
#define W_BTN            24  /* BUTTON in tree FORM */
#define X_BTN            25  /* BUTTON in tree FORM */
#define Y_BTN            26  /* BUTTON in tree FORM */
#define Z_BTN            27  /* BUTTON in tree FORM */
#define ALL_BTN          28  /* BUTTON in tree FORM */
#define INFO_BOX         29  /* BOX in tree FORM */
#define QUIT_BTN         30  /* BUTTON in tree FORM */
