/* Resource file indices for LAUNCH. */

#define MAIN             0   /* Form/Dialog-box */
#define FORM_ROOT        0   /* BOX in tree MAIN */
#define NUM_BTN          1   /* BUTTON in tree MAIN */
#define A_BTN            2   /* BUTTON in tree MAIN */
#define B_BTN            3   /* BUTTON in tree MAIN */
#define C_BTN            4   /* BUTTON in tree MAIN */
#define D_BTN            5   /* BUTTON in tree MAIN */
#define E_BTN            6   /* BUTTON in tree MAIN */
#define F_BTN            7   /* BUTTON in tree MAIN */
#define G_BTN            8   /* BUTTON in tree MAIN */
#define H_BTN            9   /* BUTTON in tree MAIN */
#define I_BTN            10  /* BUTTON in tree MAIN */
#define J_BTN            11  /* BUTTON in tree MAIN */
#define K_BTN            12  /* BUTTON in tree MAIN */
#define L_BTN            13  /* BUTTON in tree MAIN */
#define M_BTN            14  /* BUTTON in tree MAIN */
#define N_BTN            15  /* BUTTON in tree MAIN */
#define O_BTN            16  /* BUTTON in tree MAIN */
#define P_BTN            17  /* BUTTON in tree MAIN */
#define Q_BTN            18  /* BUTTON in tree MAIN */
#define R_BTN            19  /* BUTTON in tree MAIN */
#define S_BTN            20  /* BUTTON in tree MAIN */
#define T_BTN            21  /* BUTTON in tree MAIN */
#define U_BTN            22  /* BUTTON in tree MAIN */
#define V_BTN            23  /* BUTTON in tree MAIN */
#define W_BTN            24  /* BUTTON in tree MAIN */
#define X_BTN            25  /* BUTTON in tree MAIN */
#define Y_BTN            26  /* BUTTON in tree MAIN */
#define Z_BTN            27  /* BUTTON in tree MAIN */
#define ALL_BTN          28  /* BUTTON in tree MAIN */
#define ADD_BTN          29  /* BUTTON in tree MAIN */
#define QUIT_BTN         30  /* BUTTON in tree MAIN */
#define LIST_BOX         31  /* BOX in tree MAIN */
#define RM_BTN           32  /* BUTTON in tree MAIN */
#define SAVE_BTN         33  /* BUTTON in tree MAIN */

#define NEW_ITEM         1   /* Form/Dialog-box */
#define NEW_ITEM_ROOT    0   /* BOX in tree NEW_ITEM */
#define OK_BTN           1   /* BUTTON in tree NEW_ITEM */
#define CANCEL_BTN       2   /* BUTTON in tree NEW_ITEM */
#define EXEC_TXT         3   /* TEXT in tree NEW_ITEM */
#define FSEL_BTN         4   /* BUTTON in tree NEW_ITEM */
#define EXEC_STR         5   /* TEXT in tree NEW_ITEM */
#define NAME_TXT         6   /* FTEXT in tree NEW_ITEM */
