
MENU      EQU    0   ; Menu-tree 
M_DESK      EQU  3   ; TITLE in tree MENU 
M_FILE      EQU  4   ; TITLE in tree MENU 
M_DESK_INFO EQU  7   ; STRING in tree MENU 
M_FILE_QUIT EQU  16  ; STRING in tree MENU 

FORM      EQU    1   ; Form/Dialog-box 
FORM_ROOT EQU    0   ; BOX in tree FORM 
NUM_BTN      EQU 1   ; BUTTON in tree FORM 
A_BTN      EQU   2   ; BUTTON in tree FORM 
B_BTN      EQU   3   ; BUTTON in tree FORM 
C_BTN      EQU   4   ; BUTTON in tree FORM 
D_BTN      EQU   5   ; BUTTON in tree FORM 
E_BTN      EQU   6   ; BUTTON in tree FORM 
F_BTN      EQU   7   ; BUTTON in tree FORM 
G_BTN      EQU   8   ; BUTTON in tree FORM 
H_BTN      EQU   9   ; BUTTON in tree FORM 
I_BTN      EQU   10  ; BUTTON in tree FORM 
J_BTN      EQU   11  ; BUTTON in tree FORM 
K_BTN      EQU   12  ; BUTTON in tree FORM 
L_BTN      EQU   13  ; BUTTON in tree FORM 
M_BTN      EQU   14  ; BUTTON in tree FORM 
N_BTN      EQU   15  ; BUTTON in tree FORM 
O_BTN      EQU   16  ; BUTTON in tree FORM 
P_BTN      EQU   17  ; BUTTON in tree FORM 
Q_BTN      EQU   18  ; BUTTON in tree FORM 
R_BTN      EQU   19  ; BUTTON in tree FORM 
S_BTN      EQU   20  ; BUTTON in tree FORM 
T_BTN      EQU   21  ; BUTTON in tree FORM 
U_BTN      EQU   22  ; BUTTON in tree FORM 
V_BTN      EQU   23  ; BUTTON in tree FORM 
W_BTN      EQU   24  ; BUTTON in tree FORM 
X_BTN      EQU   25  ; BUTTON in tree FORM 
Y_BTN      EQU   26  ; BUTTON in tree FORM 
Z_BTN      EQU   27  ; BUTTON in tree FORM 
ALL_BTN      EQU 28  ; BUTTON in tree FORM 
CONF_BTN EQU        29  ; BUTTON in tree FORM 
QUIT_BTN EQU     30  ; BUTTON in tree FORM 
