;  ______   ______   __  __    
; /\  __ \ /\  ___\ /\ \_\ \  
; \ \  __ \\ \___  \\ \  __ \  
;  \ \_\ \_\\/\_____\\ \_\ \_\ 
;   \/_/\/_/ \/_____/ \/_/\/_/ 
;      ash@octronic.co.uk      
;
;   ASCII.S 
;       Ascii Constants

ASCII_NUL           equ	$00 ;   NULL
ASCII_SOH           equ	$01 ;   Start of Heading
ASCII_STX           equ	$02 ;   Start of Text
ASCII_ETX           equ	$03 ;   End of Text
ASCII_EOT           equ	$04 ;   End of Transmission
ASCII_ENQ           equ	$05 ;   Enquiry
ASCII_ACK           equ	$06 ;   Acknowledge
ASCII_BEL           equ	$07 ;   Bell    
ASCII_BS            equ	$08 ;   BackSpace
ASCII_TAB           equ	$09 ;   Horizontal Tab    
ASCII_LF            equ	$0a ;   Line Feed
ASCII_VT            equ	$0b ;   Vertical Tab
ASCII_FF            equ	$0c ;   New Page
ASCII_CR	        equ	$0d ;   Carriage Return
ASCII_SO	        equ	$0e ;   Shift Out
ASCII_SI   	        equ	$0f ;   Shift In
ASCII_DLE           equ	$10 ;   Data Link Escape
ASCII_DC1	        equ	$11 ;   Device Control 1
ASCII_DC2	        equ	$12 ;   Device Control 2
ASCII_DC3	        equ	$13 ;   Device Control 3 
ASCII_DC4	        equ	$14 ;   Device Control 4 
ASCII_NAK	        equ	$15 ;   Negative Acknowledge
ASCII_SYN	        equ	$16 ;   Synchronous Idle
ASCII_ETB	        equ	$17 ;   End of Transmission Block
ASCII_CAN   	    equ	$18 ;   Cancel
ASCII_EM    	    equ	$19 ;   End of Medium
ASCII_SUB   	    equ	$1a ;   Substitute
ASCII_ESC	        equ	$1b ;   Escape
ASCII_FS	        equ	$1c ;   File Separator
ASCII_GS	        equ	$1d ;   Group Separator
ASCII_RS	        equ	$1e ;   Record Separator
ASCII_US	        equ	$1f ;   Unit Separator
ASCII_SPACE 	    equ	$20
ASCII_EXCLAMATION	equ	$21
ASCII_DOUBLE_QUOTE	equ	$22
ASCII_HASH	        equ	$23
ASCII_DOLLAR	    equ	$24
ASCII_PERCENT	    equ	$25
ASCII_AMPERSAND	    equ	$26
ASCII_SINGLE_QUOTE	equ	$27
ASCII_PAREN_L	    equ	$28
ASCII_PAREN_R	    equ	$29
ASCII_ASTERISK	    equ	$2a
ASCII_PLUS	        equ	$2b
ASCII_COMMA	        equ	$2c
ASCII_MINUS	        equ	$2d
ASCII_FULL_STOP	    equ	$2e
ASCII_FWD_SLASH	    equ	$2f
ASCII_0	            equ	$30
ASCII_1	            equ	$31
ASCII_2             equ	$32
ASCII_3	            equ	$33
ASCII_4	            equ	$34
ASCII_5	            equ	$35
ASCII_6	            equ	$36
ASCII_7	            equ	$37
ASCII_8	            equ	$38
ASCII_9	            equ	$39
ASCII_COLON	        equ	$3a
ASCII_SEMI_COLON	equ	$3b
ASCII_LESS_THAN	    equ	$3c
ASCII_EQUALS	    equ	$3d
ASCII_GREATER_THAN	equ	$3e
ASCII_QUESTION_MARK	equ	$3f
ASCII_AT_SYMBOL	    equ	$40
ASCII_A	            equ	$41
ASCII_B	            equ	$42
ASCII_C	            equ	$43
ASCII_D	            equ	$44
ASCII_E	            equ	$45
ASCII_F	            equ	$46
ASCII_G	            equ	$47
ASCII_H	            equ	$48
ASCII_I	            equ	$49
ASCII_J	            equ	$4a
ASCII_K	            equ	$4b
ASCII_L	            equ	$4c
ASCII_M	            equ	$4d
ASCII_N	            equ	$4e
ASCII_O	            equ	$4f
ASCII_P	            equ	$50
ASCII_Q	            equ	$51
ASCII_R	            equ	$52
ASCII_S	            equ	$53
ASCII_T	            equ	$54
ASCII_U	            equ	$55
ASCII_V	            equ	$56
ASCII_W	            equ	$57
ASCII_X	            equ	$58
ASCII_Y	            equ	$59
ASCII_Z	            equ	$5a
ASCII_SQ_BRKT_L     equ	$5b
ASCII_BACK_SLASH	equ	$5c
ASCII_SQ_BRKT_R 	equ	$5d
ASCII_CARAT	        equ	$5e
ASCII_UNDERSCORE	equ	$5f
ASCII_BACK_TICK 	equ	$60
ASCII_a         	equ	$61
ASCII_b	        	equ	$62
ASCII_c	        	equ	$63
ASCII_d	        	equ	$64
ASCII_e	        	equ	$65
ASCII_f	        	equ	$66
ASCII_g	        	equ	$67
ASCII_h	        	equ	$68
ASCII_i	        	equ	$69
ASCII_j	        	equ	$6a
ASCII_k        		equ	$6b
ASCII_l	        	equ	$6c
ASCII_m	        	equ	$6d
ASCII_n	        	equ	$6e
ASCII_o	        	equ	$6f
ASCII_p	        	equ	$70
ASCII_q	        	equ	$71
ASCII_r	        	equ	$72
ASCII_s	        	equ	$73
ASCII_t	        	equ	$74
ASCII_u	        	equ	$75
ASCII_v	        	equ	$76
ASCII_w	        	equ	$77
ASCII_x	        	equ	$78
ASCII_y	        	equ	$79
ASCII_z	        	equ	$7a
ASCII_CURLY_L      	equ	$7b
ASCII_V_BAR         equ	$7c
ASCII_CURLY_R       equ	$7d
ASCII_TILDE         equ	$7e
ASCII_DEL           equ	$7f
