;  ______   ______   __  __    
; /\  __ \ /\  ___\ /\ \_\ \  
; \ \  __ \\ \___  \\ \  __ \  
;  \ \_\ \_\\/\_____\\ \_\ \_\ 
;   \/_/\/_/ \/_____/ \/_/\/_/ 
;      ash@octronic.co.uk      
;
;   INPUT.S 
;       Atari ST Keyboard, Mouse, Joystick Header
; Keyboard Scancodes

ESC_SCANCODE            equ 1
_1_SCANCODE              equ 2
_2_SCANCODE              equ 3
_3_SCANCODE              equ 4
_4_SCANCODE              equ 5
_5_SCANCODE              equ 6
_6_SCANCODE              equ 7
_7_SCANCODE              equ 8
_8_SCANCODE              equ 9
_9_SCANCODE              equ 10
_0_SCANCODE              equ 11
MINUS_SCANCODE          equ 12
PLUS_SCANCODE           equ 13
BACKSPACE_SCANCODE      equ 14
TAB_SCANCODE            equ 15
Q_SCANCODE              equ 16
W_SCANCODE              equ 17
E_SCANCODE              equ 18
R_SCANCODE              equ 19
T_SCANCODE              equ 20
Y_SCANCODE              equ 21
U_SCANCODE              equ 22
I_SCANCODE              equ 23
O_SCANCODE              equ 24
P_SCANCODE              equ 25
L_SQ_BRACKET_SCANCODE   equ 26
R_SQ_BRACKET_SCANCODE   equ 27
RETURN_SCANCODE         equ 28
CTRL_SCANCODE           equ 29
A_SCANCODE              equ 30
S_SCANCODE              equ 31
D_SCANCODE              equ 32
F_SCANCODE              equ 33
G_SCANCODE              equ 34
H_SCANCODE              equ 35
J_SCANCODE              equ 36
K_SCANCODE              equ 37
L_SCANCODE              equ 38
SEMICOLON_SCANCODE      equ 39
APOSTROPHIE_SCANCODE    equ 40
TILDE_SCANCODE          equ 41
L_SHIFT_SCANCODE        equ 42
BACKSLASH_SCANCODE      equ 43
Z_SCANCODE              equ 44
X_SCANCODE              equ 45
C_SCANCODE              equ 46
V_SCANCODE              equ 47
B_SCANCODE              equ 48
N_SCANCODE              equ 49
M_SCANCODE              equ 50
COMMA_SCANCODE          equ 51
FULLSTOP_SCANCODE       equ 52
FORWARD_SLASH           equ 53
RSHIFT_SCANCODE         equ 54
; 55
ALT_SCANCODE            equ 56
SPACE_SCANCODE          equ 57
CAPS_SCANCODE           equ 58
F1_SCANCODE             equ 59
F2_SCANCODE             equ 60
F3_SCANCODE             equ 61
F4_SCANCODE             equ 62
F5_SCANCODE             equ 63
F6_SCANCODE             equ 64
F7_SCANCODE             equ 65
F8_SCANCODE             equ 66
F9_SCANCODE             equ 67
F10_SCANCODE            equ 68
; 69
; 70
HOME_SCANCODE           equ 71
UP_SCANCODE             equ 72
; 73
NUM_MINUS_SCANCODE      equ 74
LEFT_SCANCODE           equ 75
; 76
RIGHT_SCANCODE          equ 77
NUM_PLUS_SCANCODE       equ 78
; 79
DOWN_SCANCODE           equ 80
; 81
INSERT_SCANCODE         equ 82
DELETE_SCANCODE         equ 83
; 84
; 85
; 86
; 87
; 88
; 89
; 90
; 91
; 92
; 93
; 94
; 95
; 96
UNDO_SCANCODE           equ 97
HELP_SCANCODE           equ 98
NUM_L_PAREN_SCANCODE    equ 99
NUM_R_PAREN_SCANCODE    equ 100
NUM_DIVIDE_SCANCODE     equ 101
NUM_MULTIPLY_SCANCODE   equ 102
NUM_7_SCANCODE          equ 103
NUM_8_SCANCODE          equ 104
NUM_9_SCANCODE          equ 105
NUM_4_SCANCODE          equ 106
NUM_5_SCANCODE          equ 107
NUM_6_SCANCODE          equ 108
NUM_1_SCANCODE          equ 109
NUM_2_SCANCODE          equ 110
NUM_3_SCANCODE          equ 111
NUM_0_SCANCODE          equ 112
NUM_DECIMAL_SCANCODE    equ 113
NUM_ENTER_SCANCODE      equ 114

